import { produce } from "immer";
import {
  BarChart2,
  Box,
  Coins,
  CreditCard,
  ShoppingCart,
  Truck,
} from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import AppTab from "~/components/core/tab/AppTab";
import useAppNav from "~/hooks/useAppNav";
import AuthService from "~/services/AuthService";
import type { TabItem } from "~/types/CommonTypes";
import {
  getB2BOrderCount,
  getB2COrderCount,
  getCoinStoreOrderCount,
  getPaymentApprovalCount,
  getReceiveOrderCount,
  getUnconfirmedOrderCount,
} from "./helper";

interface OrderListTabProps {
  activeTab?: string;
  className?: string;
}

const description = {
  "b2c-orders":
    "Sales Orders generated by the customer for the inventory of a SK Buyer/ Seller.",
  "b2b-orders": "Purchase orders between SK Buyer and SK Seller (B2B orders).",
  "receive-order":
    "Items pending to be received which have been delivered by the SK Seller.",
  "my-orders": "Purchase order placed to SK Seller.",
  "unconfirmed-orders":
    "Orders that were unconfirmed due to low stock availability.",
};

const getTabs = (isBuyer: boolean, isSeller: boolean): TabItem[] => {
  const baseTabs: TabItem[] = [];

  // Analytics tab appears in the list top tab group
  baseTabs.push({
    name: "Analytics",
    langKey: "orderAnalytics",
    key: "analytics",
    icon: <BarChart2 />,
  });

  baseTabs.push({
    name: "B2C Orders",
    langKey: "b2cOrders",
    key: "b2c-orders",
    icon: <ShoppingCart />,
  });

  baseTabs.push({
    name: "B2B Orders",
    langKey: "b2bOrders",
    key: "b2b-orders",
    icon: <Truck />,
  });

  baseTabs.push({
    name: "Payment Approval",
    langKey: "paymentApproval",
    key: "payment-approval",
    icon: <CreditCard />,
  });

  baseTabs.push({
    name: "Coin Store Orders",
    langKey: "coinStoreOrders",
    key: "coinstore-orders",
    icon: <Coins />,
  });

  baseTabs.push({
    name: "Purchase from network",
    langKey: "Purchase From Network",
    key: "my-orders",
    icon: <Box className="tw-flex-shrink-0" />,
  });

  return baseTabs;
};

const OrderListTab = ({
  activeTab = "b2c-orders",
  className = "",
}: OrderListTabProps) => {
  const { t } = useTranslation(["common"]);
  const appNav = useAppNav();

  const isBuyer = AuthService.isBuyerUser();
  const isSeller = AuthService.loggedInUserIsSeller();

  const [tabs, setTabs] = useState<TabItem[]>([]);

  const fetchedCount = useRef(false);

  const initialTab = tabs.find((tab) => tab.key === activeTab) ?? tabs[0];

  const handleTabChange = (tab: TabItem) => {
    if (tab.key === "receive-order") {
      appNav.to(`/dashboard/orders/primary/receive/list`);
    } else if (tab.key === "analytics") {
      appNav.to(`/dashboard/orders/dashboard`);
    } else {
      appNav.to(`/dashboard/orders/list`, {
        tab: tab.key,
      });
    }
  };

  useEffect(() => {
    setTabs(getTabs(isBuyer, isSeller));
  }, [isBuyer, isSeller]);

  useEffect(() => {
    // Fetch counts for tabs that are present. Use Promise.all to parallelize.
    const hasReceiveTab = tabs.some((t) => t.key === "receive-order");
    const hasB2CTab = tabs.some((t) => t.key === "b2c-orders");
    const hasB2BTab = tabs.some((t) => t.key === "b2b-orders");
    const hasCoinStoreTab = tabs.some((t) => t.key === "coinstore-orders");
    const hasUnconfirmedTab = tabs.some((t) => t.key === "unconfirmed-orders");
    const hasPaymentApprovalTab = tabs.some(
      (t) => t.key === "payment-approval",
    );
    if (
      !hasReceiveTab &&
      !hasB2CTab &&
      !hasB2BTab &&
      !hasCoinStoreTab &&
      !hasPaymentApprovalTab
    ) {
      return;
    }

    if (!hasReceiveTab && !hasB2CTab && !hasB2BTab) return;

    if (!fetchedCount) {
      return;
    }

    const fetchAll = async () => {
      const promises: Array<Promise<number | null>> = [];

      let keys: string[] = [];

      if (hasReceiveTab) {
        keys.push("receive-order");
        promises.push(getReceiveOrderCount());
      }
      if (hasB2CTab) {
        keys.push("b2c-orders");
        promises.push(getB2COrderCount());
      }
      if (hasB2BTab) {
        keys.push("b2b-orders");
        promises.push(getB2BOrderCount());
      }
      if (hasCoinStoreTab) {
        keys.push("coinstore-orders");
        promises.push(getCoinStoreOrderCount());
      }

      if (hasUnconfirmedTab) {
        keys.push("unconfirmed-orders");
        promises.push(getUnconfirmedOrderCount());
      }

      if (hasPaymentApprovalTab) {
        keys.push("payment-approval");
        promises.push(getPaymentApprovalCount());
      }
      const results = await Promise.all(promises);

      fetchedCount.current = true;

      setTabs(
        produce((draft) => {
          keys.forEach((key, index) => {
            const tab = draft.find((t) => t.key === key);
            if (tab && results[index] !== null) {
              tab.count = results[index] || 0;
            }
          });
        }),
      );
    };

    fetchAll();
  }, [tabs]);

  return (
    <div className={className}>
      <AppTab
        activeTab={initialTab?.key}
        tabs={tabs}
        onTabChange={handleTabChange}
      />
      {/* Description removed as per UI changes */}
    </div>
  );
};

export default OrderListTab;
