export const defaultSummaryData = [
  {
    label: "Total GST Collected",
    value: 0,
    key: "totalGstInward",
    color: "primary",
    valueKey: "gstCollected",
    accent: "#047857",
    caption: "From sales",
  },
  {
    label: "Total GST Inwarded",
    value: 0,
    key: "totalGstInwarded",
    color: "success",
    valueKey: "gstInwarded",
    accent: "#c2410c",
    caption: "From purchases",
  },
  {
    label: "Gst payable",
    value: 0,
    key: "gstPayable",
    color: "danger",
    valueKey: "gstPayable",
    template: 2,
    accent: "#b45309",
    caption: "Before adjustments",
    info: "Gst payable (NetGSTLiable) is the GST liability before final adjustments.",
  },
  {
    label: "Final GST to Pay",
    value: 0,
    key: "finalGstToPay",
    color: "danger",
    valueKey: "finalGstToPay",
    template: 2,
    hero: true,
    info: "Final GST to Pay (NetGSTPayable) is the GST amount after adjustments.",
  },
  {
    label: "Unique HSN Codes",
    value: 0,
    key: "uniqueHsnCodes",
    color: "warning",
    valueKey: "uniqueHsnCodes",
    accent: "#1d4ed8",
    caption: "In this period",
    isCount: true,
  },
];
