import { layout, route } from "@react-router/dev/routes";

export default [
  route(
    "dashboard/deposit-money/create",
    "routes/dashboard/deposit-money/create/index.tsx"
  ),
  route(
    "dashboard/deposit-money/options",
    "routes/dashboard/deposit-money/options/index.tsx"
  ),
  route(
    "dashboard/deposit-money/storeking",
    "routes/dashboard/deposit-money/storeking/index.tsx"
  ),
  route(
    "dashboard/deposit-money/express-deposit",
    "routes/dashboard/deposit-money/express-deposit/index.tsx"
  ),
  route(
    "dashboard/deposit-money/list",
    "routes/dashboard/deposit-money/list/index.tsx"
  ),
  route(
    "dashboard/accounts/record-payment",
    "routes/dashboard/accounts/record-payment/manage/index.tsx"
  ),
  route(
    "dashboard/accounts/platform-fee/benefits",
    "routes/dashboard/accounts/platform-fee/benefits/index.tsx"
  ),
  route(
    "dashboard/accounts/platform-fee/compare",
    "routes/dashboard/accounts/platform-fee/compare/index.tsx"
  ),
  route(
    "dashboard/accounts/platform-fee/buy-plan",
    "routes/dashboard/accounts/platform-fee/buy-plan/index.tsx"
  ),
  route(
    "dashboard/accounts/platform-fee/tiers",
    "routes/dashboard/accounts/platform-fee/tiers/index.tsx"
  ),
  layout("routes/dashboard/accounts/layout/layout.tsx", [
    route(
      "dashboard/accounts/revenue",
      "routes/dashboard/accounts/revenue/index.tsx"
    ),
    route(
      "dashboard/accounts/payables",
      "routes/dashboard/accounts/payables/index.tsx"
    ),
    route(
      "dashboard/accounts/transactions",
      "routes/dashboard/accounts/transactions/index.tsx"
    ),
    route(
      "dashboard/accounts/overall-statement",
      "routes/dashboard/accounts/overall-statement/index.tsx"
    ),
    route(
      "dashboard/accounts/money-in",
      "routes/dashboard/accounts/money-in/index.tsx"
    ),
    route(
      "dashboard/accounts/money-out",
      "routes/dashboard/accounts/money-out/index.tsx"
    ),
    route(
      "dashboard/accounts/profit-loss",
      "routes/dashboard/accounts/profit-loss/index.tsx"
    ),
    route(
      "dashboard/accounts/summary",
      "routes/dashboard/accounts/summary/index.tsx"
    ),
    route(
      "dashboard/accounts/sk-statement",
      "routes/dashboard/accounts/sk-statement/index.tsx"
    ),
    route(
      "dashboard/accounts/purchase-commission",
      "routes/dashboard/accounts/purchase-commission/index.tsx"
    ),
    route(
      "dashboard/accounts/platform-fee",
      "routes/dashboard/accounts/platform-fee/plans/index.tsx"
    ),
    route(
      "dashboard/accounts/platform-fee/statement",
      "routes/dashboard/accounts/platform-fee/statement/index.tsx"
    ),
  ]),
];
