import { route } from "@react-router/dev/routes";

import { layout } from "@react-router/dev/routes";

const productViewRoutes = [
  route(
    "dashboard/inventory/products/view/:id",
    "routes/dashboard/inventory/products/view/overview/index.tsx",
  ),
  route(
    "dashboard/inventory/products/view/:id/analytics",
    "routes/dashboard/inventory/products/view/analytics/index.tsx",
  ),
  route(
    "dashboard/inventory/products/view/:id/vendors",
    "routes/dashboard/inventory/products/view/vendors/index.tsx",
  ),
  route(
    "dashboard/inventory/products/view/:id/sales-history",
    "routes/dashboard/inventory/products/view/sales-history/index.tsx",
  ),
  route(
    "dashboard/inventory/products/view/:id/stock-ledger",
    "routes/dashboard/inventory/products/view/stock-ledger/index.tsx",
  ),
  route(
    "dashboard/inventory/products/view/:id/purchase-history",
    "routes/dashboard/inventory/products/view/purchase-history/index.tsx",
  ),
  route(
    "dashboard/inventory/products/view/:id/price-changes",
    "routes/dashboard/inventory/products/view/price-changes/index.tsx",
  ),
];

const subscribeRoutes = [
  route(
    "dashboard/inventory/subscribe/search",
    "routes/dashboard/inventory/subscribe/search/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/browse-category",
    "routes/dashboard/inventory/subscribe/browse-category/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/browse-brands",
    "routes/dashboard/inventory/subscribe/browse-brands/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/un-brands",
    "routes/dashboard/inventory/subscribe/un-brands/index.tsx",
  ),
];

const approvalHistoryRoutes = [
  route(
    "dashboard/inventory/subscribe/approval-history/products",
    "routes/dashboard/inventory/subscribe/approval-history/products/list/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/approval-history/bulk-upload",
    "routes/dashboard/inventory/subscribe/approval-history/bulk/list/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/approval-history/subscribe-pending",
    "routes/dashboard/inventory/subscribe/approval-history/subscribe-pending/list/index.tsx",
  ),
];

export default [
  route(
    "dashboard/inventory/dashboard",
    "routes/dashboard/inventory/dashboard/index.tsx",
  ),
  route(
    "dashboard/inventory/rack-bin",
    "routes/dashboard/inventory/rack-bin/index.tsx",
  ),
  route(
    "dashboard/inventory/rack-bin/bin/view/:binId",
    "routes/dashboard/inventory/rack-bin/bin/view/index.tsx",
  ),
  route(
    "dashboard/inventory/products/list",
    "routes/dashboard/inventory/products/list/index.tsx",
  ),
  route(
    "dashboard/inventory/products/config",
    "routes/dashboard/inventory/products/config/index.tsx",
  ),
  route(
    "dashboard/inventory/products/missing-config",
    "routes/dashboard/inventory/products/missing-config/index.tsx",
  ),
  route(
    "dashboard/inventory/products/velocity",
    "routes/dashboard/inventory/products/velocity/index.tsx",
  ),
  route(
    "dashboard/inventory/stock-master/list",
    "routes/dashboard/inventory/stock-master/list/index.tsx",
  ),
  layout(
    "routes/dashboard/inventory/products/view/layout.tsx",
    productViewRoutes,
  ),
  route(
    "dashboard/inventory/stock-alerts",
    "routes/dashboard/inventory/stock-alerts/index.tsx",
  ),
  route(
    "dashboard/inventory/browse-category",
    "routes/dashboard/inventory/browse-category/index.tsx",
  ),
  route(
    "dashboard/inventory/purchase-basket",
    "routes/dashboard/inventory/purchase-basket/index.tsx",
  ),
  layout(
    "routes/dashboard/inventory/subscribe/layout/layout.tsx",
    subscribeRoutes,
  ),
  route(
    "dashboard/inventory/subscribe/add-product",
    "routes/dashboard/inventory/subscribe/add-product/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/ai-add-product",
    "routes/dashboard/inventory/subscribe/ai-add-product/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/product-detail/:id",
    "routes/dashboard/inventory/subscribe/product-detail/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/cart",
    "routes/dashboard/inventory/subscribe/cart/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/add-product/bulk",
    "routes/dashboard/inventory/subscribe/bulk-upload/products/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/bulk-upload/barcode",
    "routes/dashboard/inventory/subscribe/bulk-upload/barcode/index.tsx",
  ),
  layout(
    "routes/dashboard/inventory/subscribe/approval-history/layout/layout.tsx",
    approvalHistoryRoutes,
  ),
  route(
    "dashboard/inventory/subscribe/bulk-upload/invalid-barcodes",
    "routes/dashboard/inventory/subscribe/bulk-upload/invalid-barcodes/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/approval-history/products/view/:id",
    "routes/dashboard/inventory/subscribe/approval-history/products/view/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/approval-history/bulk-upload/view/:id",
    "routes/dashboard/inventory/subscribe/approval-history/bulk/view/index.tsx",
  ),
  route(
    "dashboard/inventory/browse",
    "routes/dashboard/inventory/browse/index.tsx",
  ),
  route(
    "dashboard/inventory/cases",
    "routes/dashboard/inventory/cases/index.tsx",
  ),
  route(
    "dashboard/inventory/bulk-update",
    "routes/dashboard/inventory/bulk-update/index.tsx",
  ),
  route(
    "dashboard/inventory/barcode-scan",
    "routes/dashboard/inventory/barcode-scan/index.tsx",
  ),
  route(
    "dashboard/inventory/barcode-scan-v1",
    "routes/dashboard/inventory/barcode-scan-v1/index.tsx",
  ),
  route(
    "dashboard/inventory/barcode-scan-bulk",
    "routes/dashboard/inventory/barcode-scan-bulk/index.tsx",
  ),
  route(
    "dashboard/inventory/barcode-scan-bulk-items",
    "routes/dashboard/inventory/barcode-scan-bulk-items/index.tsx",
  ),
  route(
    "dashboard/inventory/subscribe/main",
    "routes/dashboard/inventory/subscribe/main/index.tsx",
  ),
  route(
    "dashboard/inventory/print-barcode",
    "routes/dashboard/inventory/print-barcode/deal/index.tsx",
  ),
  route(
    "dashboard/inventory/print-barcode/generator",
    "routes/dashboard/inventory/print-barcode/generator/index.tsx",
  ),
  route(
    "dashboard/inventory/print-barcode/bulk",
    "routes/dashboard/inventory/print-barcode/bulk/index.tsx",
  ),
];
