import { route } from "@react-router/dev/routes";

export default [
  route(
    "dashboard/purchase-order/main",
    "routes/dashboard/purchase-order/main/index.tsx"
  ),
  route(
    "dashboard/purchase-order/list",
    "routes/dashboard/purchase-order/list/index.tsx"
  ),
  route(
    "dashboard/purchase-order/view/:id",
    "routes/dashboard/purchase-order/view/index.tsx"
  ),
  route(
    "dashboard/purchase-order/manage",
    "routes/dashboard/purchase-order/manage/index.tsx"
  ),
  route(
    "dashboard/purchase-order/vendors",
    "routes/dashboard/purchase-order/vendors/index.tsx"
  ),
  route(
    "dashboard/purchase-order/process/:id",
    "routes/dashboard/purchase-order/process/index.tsx"
  ),
  route(
    "dashboard/purchase-order/recently-received",
    "routes/dashboard/purchase-order/recently-received/index.tsx"
  ),
  route(
    "dashboard/purchase-order/auto-allocation",
    "routes/dashboard/purchase-order/auto-allocation/index.tsx"
  ),
  route(
    "dashboard/purchase-order/summary",
    "routes/dashboard/purchase-order/summary/index.tsx"
  ),
  route(
    "dashboard/purchase-order/summary-vendors",
    "routes/dashboard/purchase-order/summary-vendors/index.tsx"
  ),
  route(
    "dashboard/purchase-order/summary-po",
    "routes/dashboard/purchase-order/summary-po/index.tsx"
  ),
  route(
    "dashboard/purchase-order/box-receive",
    "routes/dashboard/purchase-order/box-receive/index.tsx"
  ),
  route(
    "dashboard/purchase-order/not-received",
    "routes/dashboard/purchase-order/not-received/index.tsx"
  ),
  route(
    "dashboard/purchase-order/seller-summary",
    "routes/dashboard/purchase-order/seller-summary/index.tsx"
  ),
  route(
    "dashboard/purchase-order/summary-retailers",
    "routes/dashboard/purchase-order/summary-retailers/index.tsx"
  ),
];
